spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_notificationsserver?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8088
reaktor:
  publicKeyFile: C:\claves\public_key.pem
  urlCors: http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173, http://localhost:8084
  firebase_server_url: https://api.iesjandula.es/
  notifications_server_url: https://api.iesjandula.es/
  clientId: notifications
  reiniciarParametros: true
  constantes:
    notificationsMaxCalendar: 10
    notificationsMaxEmail: 10
    notificationsMaxWeb: 10
  http_connection_timeout: 30000
  gmail:
    appName: nombre de la aplicaci√≥n
    from: "tucorreo@gmail.com"
    oauthCredentialsFile: C:\claves\gmail_oauth_credentials.json