spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_notificationsserver?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8088
logging:
    level:
        root: INFO
    file:
        name: /tmp/reaktor_notificationsserver.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB

reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  privateKeyFile: ${PRIVATE_KEY_FILE}
  googleCredentialsFile: ${GOOGLE_CREDENTIALS_FILE}
  urlCors: https://somos.iesjandula.es
  firebase_server_url: https://api.iesjandula.es/
  notifications_server_url: https://api.iesjandula.es/
  clientId: notifications
  constantes:
    notificationsMaxCalendar: 10
    notificationsMaxEmail: 10
    notificationsMaxWeb: 10
  http_connection_timeout: 30000
  gmail:
    from: "reaktor-notifications-server@gmail.com"
    oauthCredentialsFile: ${GMAIL_OAUTH_CREDENTIALS_FILE}