# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        os: [linux]

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Secreto para la contraseña de la base de datos
        PUBLIC_KEY_FILE: ${{ secrets.PUBLIC_KEY_FILE }} # Secreto para la clave pública para JWT
        CLIENT_ID: ${{ secrets.CLIENT_ID }} # Secreto para el ID del cliente
        GMAIL_APP_NAME: ${{ secrets.GMAIL_APP_NAME }} # Secreto para el nombre de la aplicación de Gmail
        GMAIL_EMAIL_FROM: ${{ secrets.GMAIL_EMAIL_FROM }} # Secreto para el correo electrónico de Gmail
        GMAIL_OAUTH_CREDENTIALS_FILE: ${{ secrets.GMAIL_OAUTH_CREDENTIALS_FILE }} # Secreto para el archivo de credenciales de OAuth de Gmail
      run: |
        echo "DB_PASSWORD=${DB_PASSWORD}" > src/main/resources/application-VPS-filter.properties
        echo "PUBLIC_KEY_FILE=${PUBLIC_KEY_FILE}" >> src/main/resources/application-VPS-filter.properties
        echo "CLIENT_ID=${CLIENT_ID}" >> src/main/resources/application-VPS-filter.properties
        echo "GMAIL_APP_NAME=${GMAIL_APP_NAME}" >> src/main/resources/application-VPS-filter.properties
        echo "GMAIL_EMAIL_FROM=${GMAIL_EMAIL_FROM}" >> src/main/resources/application-VPS-filter.properties
        echo "GMAIL_OAUTH_CREDENTIALS_FILE=${GMAIL_OAUTH_CREDENTIALS_FILE}" >> src/main/resources/application-VPS-filter.properties
        mvn clean install -Dspring.config.location=src/main/resources/application-VPS.yaml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
